
ALTER TABLE public.ordenar_passos ADD COLUMN explicacao text;

UPDATE public.ordenar_passos SET explicacao = 'O modelo cascata segue uma sequência linear: primeiro entendemos o que precisa ser feito (requisitos), analisamos, projetamos a solução, codificamos, testamos, colocamos em uso e depois mantemos.' WHERE titulo = 'Ciclo de Vida do Software (Cascata)';
UPDATE public.ordenar_passos SET explicacao = 'A normalização é um processo incremental: começamos com dados brutos e aplicamos cada forma normal em sequência, eliminando redundâncias progressivamente — primeiro grupos repetitivos, depois dependências parciais e por fim transitivas.' WHERE titulo = 'Normalização de Banco de Dados';
UPDATE public.ordenar_passos SET explicacao = 'O login segue um fluxo de validação em camadas: o usuário fornece credenciais, o sistema valida localmente, consulta o banco, compara de forma segura (hash), e só então cria uma sessão autenticada.' WHERE titulo = 'Processo de Login com Autenticação';
UPDATE public.ordenar_passos SET explicacao = 'No Scrum, cada Sprint começa com planejamento, tem acompanhamento diário, e termina com uma revisão do produto entregue seguida de uma retrospectiva do processo da equipe.' WHERE titulo = 'Metodologia Scrum - Fluxo de uma Sprint';
UPDATE public.ordenar_passos SET explicacao = 'O modelo OSI organiza a comunicação em rede do nível mais físico (cabos e sinais) até o mais abstrato (aplicações que o usuário interage). Pense: do hardware ao software.' WHERE titulo = 'Modelo OSI - Camadas de Rede';
UPDATE public.ordenar_passos SET explicacao = 'A compilação transforma código legível em código executável: primeiro analisa a estrutura do texto (léxica, sintática, semântica), depois gera e otimiza o código de máquina, e por fim linkedita as dependências.' WHERE titulo = 'Compilação de um Programa';
UPDATE public.ordenar_passos SET explicacao = 'O deploy segue o princípio de integração contínua: código é versionado, testado automaticamente, empacotado, validado em staging e só então vai para produção.' WHERE titulo = 'Processo de Deploy de uma Aplicação Web';
UPDATE public.ordenar_passos SET explicacao = 'Criar um banco de dados começa no abstrato (entender os dados e modelar) e vai até o concreto (criar tabelas, inserir dados e configurar). É do conceitual ao físico.' WHERE titulo = 'Criação de um Banco de Dados Relacional';
UPDATE public.ordenar_passos SET explicacao = 'Resolver problemas com algoritmos segue o pensamento computacional: entender → planejar → pseudocodificar → implementar → testar → refinar. Nunca comece codificando!' WHERE titulo = 'Resolução de um Problema com Algoritmo';
UPDATE public.ordenar_passos SET explicacao = 'Uma requisição HTTP passa por várias camadas: o navegador precisa descobrir o IP (DNS), estabelecer conexão (TCP), enviar o pedido, e o servidor processa e responde para o navegador renderizar.' WHERE titulo = 'Fluxo de uma Requisição HTTP';
UPDATE public.ordenar_passos SET explicacao = 'O RUP é iterativo mas tem 4 fases sequenciais: primeiro define-se o escopo (concepção), depois a arquitetura (elaboração), então constrói-se o sistema, e por fim faz a transição para o usuário.' WHERE titulo = 'Metodologia RUP - Fases';
UPDATE public.ordenar_passos SET explicacao = 'A hierarquia de memória é organizada por velocidade e custo: quanto mais perto do processador, mais rápida e cara. Registradores são os mais rápidos, armazenamento em nuvem o mais lento.' WHERE titulo LIKE 'Hierarquia de Memória%';
UPDATE public.ordenar_passos SET explicacao = 'Engenharia de requisitos é um processo iterativo que vai da descoberta (elicitação) até o controle de mudanças, passando por análise, documentação e validação com stakeholders.' WHERE titulo = 'Processo de Engenharia de Requisitos';
UPDATE public.ordenar_passos SET explicacao = 'ML segue um pipeline de dados: coletar → limpar → explorar → selecionar features → treinar → avaliar → deploy. A qualidade dos dados nas etapas iniciais determina o sucesso do modelo.' WHERE titulo = 'Pipeline de Machine Learning';
UPDATE public.ordenar_passos SET explicacao = 'O PDCA é um ciclo de melhoria contínua: planeja-se a mudança, executa-se, verifica-se os resultados e age-se para padronizar ou corrigir. Depois recomeça!' WHERE titulo = 'Ciclo PDCA (Melhoria Contínua)';
UPDATE public.ordenar_passos SET explicacao = 'Teste de software é sistemático: primeiro planeja, cria os casos, prepara o ambiente, executa, registra resultados, analisa os bugs encontrados e faz reteste após correções.' WHERE titulo = 'Processo de Teste de Software';
UPDATE public.ordenar_passos SET explicacao = 'O boot começa no hardware (POST verifica componentes), passa pelo firmware (BIOS/UEFI), carrega o sistema operacional (kernel), inicializa serviços e finalmente mostra a tela de login.' WHERE titulo = 'Boot de um Sistema Operacional';
UPDATE public.ordenar_passos SET explicacao = 'Casos de uso em UML começam identificando quem interage (atores) e o que fazem (casos de uso), depois detalham os fluxos (principal, alternativo, exceção) e por fim criam o diagrama visual.' WHERE titulo LIKE 'Desenvolvimento de um Caso de Uso%';
UPDATE public.ordenar_passos SET explicacao = 'O three-way handshake é como um cumprimento: um lado diz "oi" (SYN), o outro responde "oi, te ouvi" (SYN-ACK), e o primeiro confirma "também te ouvi" (ACK). Aí a conexão está pronta.' WHERE titulo LIKE 'Protocolo TCP%';
UPDATE public.ordenar_passos SET explicacao = 'Git segue um fluxo: inicia o repositório, faz alterações, adiciona ao staging, commita (salva localmente), envia ao remoto, passa por revisão e então é integrado à branch principal.' WHERE titulo LIKE 'Processo de Versionamento%';
