
-- Criar curso de JavaScript
DO $$
DECLARE
  v_curso_id uuid;
  v_mod1_id uuid;
  v_mod2_id uuid;
  v_mod3_id uuid;
  v_mod4_id uuid;
  v_mod5_id uuid;
  v_mod6_id uuid;
BEGIN
  -- Curso
  INSERT INTO public.cursos (nome, descricao, icone, ordem)
  VALUES ('JavaScript', 'Curso completo de JavaScript nível universitário — do zero ao avançado, com exemplos práticos e analogias do dia a dia.', 'FileCode', 10)
  RETURNING id INTO v_curso_id;

  -- Módulo 1: Fundamentos
  INSERT INTO public.modulos (curso_id, nome, descricao, icone, ordem)
  VALUES (v_curso_id, 'Fundamentos de JavaScript', 'Variáveis, tipos de dados e operadores — a base de tudo.', 'Code', 0)
  RETURNING id INTO v_mod1_id;

  INSERT INTO public.modulo_topicos (modulo_id, titulo, conteudo, ordem, moedas) VALUES
  (v_mod1_id, 'Variáveis e Declarações', E'## Variáveis: As Caixas do Programador\n\nImagine que você tem várias **caixas organizadoras** em casa. Cada caixa tem uma **etiqueta** (nome) e guarda algo dentro (valor). É exatamente isso que uma variável faz!\n\n### As 3 formas de criar variáveis\n\n```javascript\nvar nome = \"Maria\";    // forma antiga (evite!)\nlet idade = 25;        // pode mudar depois\nconst PI = 3.14159;    // nunca muda\n```\n\n### Diferenças importantes\n\n| Palavra-chave | Pode mudar? | Escopo | Quando usar |\n|--------------|-------------|--------|-------------|\n| `var` | ✅ Sim | Função | ❌ Evite sempre |\n| `let` | ✅ Sim | Bloco | ✅ Quando o valor muda |\n| `const` | ❌ Não | Bloco | ✅ Padrão preferido |\n\n### Analogia do Quadro Branco\n\n- **`let`** é como escrever a lápis — você pode apagar e reescrever\n- **`const`** é como escrever com caneta permanente — não dá pra mudar\n- **`var`** é como escrever num papel solto — pode se perder facilmente\n\n### Regras de nomeação\n\n```javascript\n// ✅ Válidos\nlet nomeCompleto = \"João Silva\";\nlet _privado = true;\nlet $valor = 100;\n\n// ❌ Inválidos\nlet 2nome = \"erro\";     // não começa com número\nlet class = \"erro\";     // palavra reservada\n```\n\n### Hoisting: O Elevador Invisível\n\nO JavaScript \"sobe\" as declarações `var` para o topo do código antes de executar:\n\n```javascript\nconsole.log(x); // undefined (não dá erro!)\nvar x = 5;\n\nconsole.log(y); // ❌ ReferenceError!\nlet y = 10;\n```\n\n> 💡 **Regra de ouro**: Use `const` por padrão. Só use `let` quando precisar reatribuir. Nunca use `var`.\n\n### Exercício Mental\nSe você declarar `const frutas = [\"maçã\", \"banana\"]` e depois fizer `frutas.push(\"uva\")`, vai dar erro? **Não!** Porque `const` impede a **reatribuição**, mas não impede **mutação** do conteúdo.', 0, 5),
  (v_mod1_id, 'Tipos de Dados', E'## Tipos de Dados: Os Ingredientes da Programação\n\nPense numa receita de bolo. Você precisa de diferentes tipos de ingredientes: farinha (sólido), leite (líquido), ovos (unidades). Na programação é igual — temos diferentes **tipos de dados** para representar diferentes informações.\n\n### Tipos Primitivos\n\n| Tipo | Exemplo | Analogia |\n|------|---------|----------|\n| `string` | `\"Olá mundo\"` | Um texto escrito num papel |\n| `number` | `42`, `3.14` | Um número na calculadora |\n| `boolean` | `true`, `false` | Um interruptor de luz |\n| `undefined` | `undefined` | Uma caixa vazia que nunca foi preenchida |\n| `null` | `null` | Uma caixa intencionalmente esvaziada |\n\n### Strings: O Texto\n\n```javascript\nlet nome = \"JavaScript\";\nlet template = `Meu nome é ${nome}`; // template literal ✨\n\nnome.length;          // 10\nnome.toUpperCase();   // \"JAVASCRIPT\"\nnome.includes(\"Script\"); // true\nnome.slice(0, 4);     // \"Java\"\n```\n\n### Numbers: Os Números\n\n```javascript\nlet inteiro = 42;\nlet decimal = 3.14;\n\n// Cuidado com ponto flutuante!\n0.1 + 0.2; // 0.30000000000000004 😱\n\nNumber(\"42\");     // 42\nparseInt(\"3.14\"); // 3\n```\n\n### Booleans: Verdadeiro ou Falso\n\n```javascript\n// Valores \"falsy\" (viram false)\n// 0, \"\", null, undefined, NaN, false\n\n// Valores \"truthy\" (viram true)\n// Todo o resto! \"0\", \" \", [], {}\n```\n\n### typeof: O Detetive de Tipos\n\n```javascript\ntypeof \"hello\";    // \"string\"\ntypeof 42;         // \"number\"\ntypeof true;       // \"boolean\"\ntypeof null;       // \"object\" 🐛 (bug histórico!)\ntypeof [];         // \"object\"\n```\n\n> 💡 **Dica**: Use `Array.isArray([])` para verificar arrays.\n\n### Exercício Mental\nO que `typeof NaN` retorna? Surpreendentemente, `\"number\"`! NaN significa \"Not a Number\", mas seu **tipo** é number.', 1, 5),
  (v_mod1_id, 'Operadores', E'## Operadores: As Ferramentas de Cálculo\n\nOperadores são como as ferramentas de uma oficina — cada um tem uma função específica.\n\n### Operadores Aritméticos\n\n```javascript\nlet a = 10, b = 3;\na + b;   // 13\na - b;   // 7\na * b;   // 30\na / b;   // 3.333...\na % b;   // 1 (resto)\na ** b;  // 1000 (potenciação)\n```\n\n### Comparação: == vs ===\n\n| Operador | Significado | Exemplo | Resultado |\n|----------|------------|---------|----------|\n| `==` | Igual (valor) | `5 == \"5\"` | `true` ⚠️ |\n| `===` | Igual (valor+tipo) | `5 === \"5\"` | `false` ✅ |\n| `!=` | Diferente | `5 != \"5\"` | `false` |\n| `!==` | Estritamente diferente | `5 !== \"5\"` | `true` |\n\n```javascript\n0 == false;     // true 😰\n0 === false;    // false ✅\n```\n\n> 🎯 **Regra de ouro**: SEMPRE use `===` e `!==`.\n\n### Operadores Lógicos\n\n```javascript\ntrue && true;   // true (AND)\ntrue || false;  // true (OR)\n!true;          // false (NOT)\n```\n\n**Analogia do Portão**:\n- `&&` = Duas chaves necessárias\n- `||` = Qualquer chave serve\n- `!` = Inverte o estado\n\n### Operador Ternário\n\n```javascript\nlet idade = 20;\nlet status = idade >= 18 ? \"Maior\" : \"Menor\";\n```\n\n### Exercício Mental\nO que retorna `[] == ![]`? Incrivelmente, `true`! Coerção de tipos do `==`. Mais um motivo para sempre usar `===`.', 2, 5);

  -- Módulo 2: Estruturas de Controle
  INSERT INTO public.modulos (curso_id, nome, descricao, icone, ordem)
  VALUES (v_curso_id, 'Estruturas de Controle', 'Condicionais e loops — controlando o fluxo do programa.', 'GitBranch', 1)
  RETURNING id INTO v_mod2_id;

  INSERT INTO public.modulo_topicos (modulo_id, titulo, conteudo, ordem, moedas) VALUES
  (v_mod2_id, 'Condicionais: if, else e switch', E'## Condicionais: As Encruzilhadas do Código\n\nImagine que você está dirigindo e chega numa bifurcação. Se virar à esquerda, vai pro trabalho. Se virar à direita, vai pra casa.\n\n### if / else\n\n```javascript\nlet hora = 14;\n\nif (hora < 12) {\n  console.log(\"Bom dia! ☀️\");\n} else if (hora < 18) {\n  console.log(\"Boa tarde! 🌤️\");\n} else {\n  console.log(\"Boa noite! 🌙\");\n}\n```\n\n### Analogia do Semáforo\n\n| Cor | Ação | Em código |\n|-----|------|----------|\n| 🟢 Verde | Passe | `if (sinal === \"verde\") { andar(); }` |\n| 🟡 Amarelo | Atenção | `else if (sinal === \"amarelo\") { reduzir(); }` |\n| 🔴 Vermelho | Pare | `else { parar(); }` |\n\n### switch: O Menu de Opções\n\n```javascript\nlet dia = 3;\nswitch (dia) {\n  case 1: console.log(\"Segunda\"); break;\n  case 2: console.log(\"Terça\"); break;\n  case 3: console.log(\"Quarta\"); break;\n  case 5: console.log(\"Sexta 🎉\"); break;\n  default: console.log(\"Final de semana!\");\n}\n```\n\n> ⚠️ Esquecer o `break` faz o código \"cair\" para o próximo case.\n\n### Nullish Coalescing (??)\n\n```javascript\nlet valor = 0;\nvalor || 10;  // 10 (0 é falsy!)\nvalor ?? 10;  // 0  (0 não é null/undefined) ✅\n```\n\n### Optional Chaining (?.)\n\n```javascript\nlet user = { endereco: { rua: \"Av. Brasil\" } };\nuser?.endereco?.rua;     // \"Av. Brasil\"\nuser?.telefone?.numero;  // undefined (sem erro!)\n```', 0, 5),
  (v_mod2_id, 'Loops: Repetindo com Inteligência', E'## Loops: A Máquina de Repetição\n\nImagine que você precisa carimbar 100 documentos. Com um loop, a máquina repete automaticamente!\n\n### for: O Loop Clássico\n\n```javascript\nfor (let i = 0; i < 5; i++) {\n  console.log(`Passo ${i}`);\n}\n```\n\n### while: Enquanto For Verdade\n\n```javascript\nlet combustivel = 100;\nwhile (combustivel > 0) {\n  console.log(`Combustível: ${combustivel}%`);\n  combustivel -= 25;\n}\n```\n\n**Analogia**: O `while` é como uma esteira de academia — continua rodando **enquanto** você estiver correndo.\n\n### for...of vs for...in\n\n```javascript\n// for...of — percorre VALORES\nlet frutas = [\"🍎\", \"🍌\", \"🍇\"];\nfor (let fruta of frutas) { console.log(fruta); }\n\n// for...in — percorre CHAVES\nlet pessoa = { nome: \"Ana\", idade: 25 };\nfor (let chave in pessoa) { console.log(`${chave}: ${pessoa[chave]}`); }\n```\n\n### Comparação Rápida\n\n| Loop | Melhor para | Exemplo |\n|------|------------|--------|\n| `for` | Contadores | Repetir N vezes |\n| `while` | Condição indefinida | Esperar input |\n| `do...while` | Pelo menos 1x | Menu de opções |\n| `for...of` | Arrays | Percorrer lista |\n| `for...in` | Objetos | Percorrer chaves |\n\n### break e continue\n\n```javascript\nfor (let i = 0; i < 10; i++) {\n  if (i === 5) break;    // sai do loop\n  if (i === 2) continue; // pula iteração\n  console.log(i);\n}\n```\n\n### Exercício Mental\n`while (true) {}` — **loop infinito**! Sempre garanta que a condição vai se tornar `false`.', 1, 5);

  -- Módulo 3: Funções e Escopo
  INSERT INTO public.modulos (curso_id, nome, descricao, icone, ordem)
  VALUES (v_curso_id, 'Funções e Escopo', 'Criando blocos reutilizáveis e entendendo escopo.', 'Workflow', 2)
  RETURNING id INTO v_mod3_id;

  INSERT INTO public.modulo_topicos (modulo_id, titulo, conteudo, ordem, moedas) VALUES
  (v_mod3_id, 'Funções e Arrow Functions', E'## Funções: As Receitas do Programador\n\nUma função é como uma **receita de cozinha**: ingredientes (parâmetros), modo de preparo (código) e resultado (retorno).\n\n### Function Declaration\n\n```javascript\nfunction saudacao(nome) {\n  return `Olá, ${nome}! 👋`;\n}\n```\n\n### Arrow Function (ES6+) ✨\n\n```javascript\nconst somar = (a, b) => a + b;\nconst quadrado = x => x ** 2;\nconst agora = () => new Date();\n```\n\n### Comparação\n\n| Tipo | Sintaxe | Hoisting? |\n|------|---------|----------|\n| Declarada | `function nome() {}` | ✅ Sim |\n| Expressão | `const nome = function() {}` | ❌ Não |\n| Arrow | `const nome = () => {}` | ❌ Não |\n\n### Parâmetros Padrão e Rest\n\n```javascript\nfunction criar(nome, papel = \"estudante\") {\n  return { nome, papel };\n}\n\nfunction somarTodos(...nums) {\n  return nums.reduce((a, n) => a + n, 0);\n}\nsomarTodos(1, 2, 3, 4, 5); // 15\n```\n\n### Funções como Valores\n\n```javascript\nfunction executar(fn, valor) {\n  return fn(valor);\n}\nexecutar(quadrado, 5); // 25\n```\n\n> 💡 Use Arrow para callbacks curtos. Para métodos de objeto, prefira funções declaradas (por causa do `this`).', 0, 5),
  (v_mod3_id, 'Escopo e Closures', E'## Escopo: Quem Pode Ver O Quê?\n\nImagine um prédio. Quem está no **térreo** (escopo global) é visível para todos. Quem está num **apartamento** (escopo local) só é visível ali dentro.\n\n### Escopo de Bloco\n\n```javascript\nif (true) {\n  let x = 10;\n  const y = 20;\n  var z = 30; // ⚠️ var ignora bloco!\n}\nconsole.log(z); // 30 (var escapa!)\nconsole.log(x); // ❌ ReferenceError\n```\n\n### Closures: A Mágica do JS\n\nUm **closure** acontece quando uma função \"lembra\" das variáveis do escopo onde foi criada.\n\n**Analogia da Mochila**: Você sai de casa levando uma mochila. Mesmo longe, ainda tem acesso ao que colocou nela.\n\n```javascript\nfunction criarContador() {\n  let contagem = 0;\n  return function() {\n    contagem++;\n    return contagem;\n  };\n}\n\nconst contador = criarContador();\ncontador(); // 1\ncontador(); // 2\ncontador(); // 3\n```\n\n### Uso Prático\n\n```javascript\nfunction criarMultiplicador(fator) {\n  return (n) => n * fator;\n}\nconst dobro = criarMultiplicador(2);\nconst triplo = criarMultiplicador(3);\ndobro(5);  // 10\ntriplo(5); // 15\n```\n\n### Armadilha com var em Loops\n\n```javascript\n// ❌ var — imprime 3, 3, 3\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100);\n}\n\n// ✅ let — imprime 0, 1, 2\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 100);\n}\n```\n\n### Exercício Mental\nClosures permitem **dados privados**. A variável `contagem` não pode ser acessada de fora — só pela função retornada. É **encapsulamento**!', 1, 5);

  -- Módulo 4: Arrays e Objetos
  INSERT INTO public.modulos (curso_id, nome, descricao, icone, ordem)
  VALUES (v_curso_id, 'Arrays e Objetos', 'Estruturas de dados fundamentais para organizar informações.', 'Database', 3)
  RETURNING id INTO v_mod4_id;

  INSERT INTO public.modulo_topicos (modulo_id, titulo, conteudo, ordem, moedas) VALUES
  (v_mod4_id, 'Arrays e Métodos Essenciais', E'## Arrays: A Lista de Compras do Programador\n\nUm array é como uma **lista de compras**: sequência ordenada de itens com posição (índice).\n\n### Métodos Mutáveis\n\n```javascript\nlet nums = [1, 2, 3];\nnums.push(4);      // [1, 2, 3, 4]\nnums.pop();        // [1, 2, 3]\nnums.unshift(0);   // [0, 1, 2, 3]\nnums.shift();      // [1, 2, 3]\n```\n\n### Métodos Imutáveis (os mais importantes!) ✨\n\n```javascript\nlet numeros = [1, 2, 3, 4, 5];\n\nnumeros.map(n => n * 2);         // [2, 4, 6, 8, 10]\nnumeros.filter(n => n % 2 === 0); // [2, 4]\nnumeros.find(n => n > 3);         // 4\nnumeros.reduce((a, n) => a + n, 0); // 15\nnumeros.some(n => n > 4);         // true\nnumeros.every(n => n > 0);        // true\n```\n\n### Analogia do Restaurante\n\n| Método | Analogia | O que faz |\n|--------|----------|----------|\n| `map` | Chef transforma pratos | Aplica função em cada item |\n| `filter` | Garçom filtra pedidos | Seleciona por condição |\n| `find` | Procurar mesa vazia | Retorna primeiro match |\n| `reduce` | Somar a conta | Acumula em um valor |\n\n### Encadeamento (Chaining)\n\n```javascript\nlet resultado = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n  .filter(n => n % 2 === 0)\n  .map(n => n ** 2)\n  .reduce((a, b) => a + b, 0); // 220\n```\n\n### Spread Operator\n\n```javascript\nlet a = [1, 2, 3];\nlet b = [4, 5, 6];\nlet c = [...a, ...b]; // [1, 2, 3, 4, 5, 6]\nlet copia = [...a];   // cópia independente\n```\n\n### Exercício Mental\n`map` retorna **novo array**. `forEach` **não retorna nada**. Use `map` quando precisa do resultado.', 0, 5),
  (v_mod4_id, 'Objetos e Destructuring', E'## Objetos: O RG do JavaScript\n\nObjetos são como **fichas cadastrais** — cada informação tem um nome (chave) e valor.\n\n```javascript\nlet pessoa = {\n  nome: \"Ana Silva\",\n  idade: 25,\n  hobbies: [\"leitura\", \"código\"]\n};\n```\n\n### Acessando Propriedades\n\n```javascript\npessoa.nome;       // \"Ana Silva\" (ponto)\npessoa[\"idade\"];   // 25 (colchetes)\n```\n\n### Destructuring: Desempacotando ✨\n\n**Analogia**: Abrir uma encomenda e separar cada item.\n\n```javascript\nlet { nome, idade } = pessoa;\nlet { nome: nomeCompleto } = pessoa; // renomear\nlet { telefone = \"N/A\" } = pessoa;   // padrão\n\nlet [primeiro, ...resto] = [1, 2, 3, 4];\n// primeiro = 1, resto = [2, 3, 4]\n```\n\n### Spread com Objetos\n\n```javascript\nlet base = { nome: \"Ana\", idade: 25 };\nlet completo = { ...base, cidade: \"SP\", idade: 26 };\n// { nome: \"Ana\", idade: 26, cidade: \"SP\" }\n```\n\n### Object Methods\n\n```javascript\nlet user = { nome: \"Ana\", idade: 25 };\nObject.keys(user);    // [\"nome\", \"idade\"]\nObject.values(user);  // [\"Ana\", 25]\nObject.entries(user); // [[\"nome\",\"Ana\"],[\"idade\",25]]\n```\n\n### Optional Chaining\n\n```javascript\nuser?.endereco?.rua; // undefined (sem erro!)\n```\n\n### JSON\n\n```javascript\nJSON.stringify(obj); // objeto → string\nJSON.parse(str);     // string → objeto\n```\n\n### Exercício Mental\n`let a = {x:1}; let b = a; b.x = 2;` — `a.x` é `2`! Objetos são por **referência**. Use `{...obj}` para copiar.', 1, 5);

  -- Módulo 5: DOM e Eventos
  INSERT INTO public.modulos (curso_id, nome, descricao, icone, ordem)
  VALUES (v_curso_id, 'DOM e Eventos', 'Interagindo com a página web.', 'Globe', 4)
  RETURNING id INTO v_mod5_id;

  INSERT INTO public.modulo_topicos (modulo_id, titulo, conteudo, ordem, moedas) VALUES
  (v_mod5_id, 'Manipulação do DOM', E'## DOM: A Árvore Viva da Página\n\nO **DOM** é a representação da página HTML como uma árvore de objetos que o JavaScript pode manipular.\n\n### Selecionando Elementos\n\n```javascript\ndocument.getElementById(\"titulo\");\ndocument.querySelector(\".btn-primary\");  // ✨ mais usado\ndocument.querySelectorAll(\".item\");\n```\n\n### Modificando Conteúdo\n\n```javascript\nlet el = document.querySelector(\"#msg\");\nel.textContent = \"Novo texto!\";\nel.innerHTML = \"<strong>Negrito</strong>\";\n```\n\n### Classes CSS (melhor prática)\n\n```javascript\nlet box = document.querySelector(\".box\");\nbox.classList.add(\"ativo\");\nbox.classList.remove(\"inativo\");\nbox.classList.toggle(\"visivel\");\n```\n\n### Criando Elementos\n\n```javascript\nlet card = document.createElement(\"div\");\ncard.className = \"card\";\ncard.textContent = \"Novo card!\";\ndocument.querySelector(\"#lista\").appendChild(card);\ncard.remove(); // remover\n```\n\n### Analogia do Teatro\n\n| Conceito | Analogia |\n|----------|----------|\n| `document` | O teatro inteiro |\n| `querySelector` | Encontrar um ator |\n| `createElement` | Contratar novo ator |\n| `appendChild` | Colocar no palco |\n| `classList` | Trocar figurino |\n\n> 💡 `textContent` = texto puro (seguro). `innerHTML` = interpreta HTML (cuidado com XSS!).', 0, 5),
  (v_mod5_id, 'Eventos e Interatividade', E'## Eventos: Ouvindo o Usuário\n\nEventos são como **sensores** numa casa inteligente — detectam ações e executam respostas.\n\n### addEventListener\n\n```javascript\nlet btn = document.querySelector(\"#meuBtn\");\nbtn.addEventListener(\"click\", () => {\n  console.log(\"Clicado! 🎉\");\n});\n```\n\n### Eventos Comuns\n\n| Evento | Quando dispara |\n|--------|---------------|\n| `click` | Clique do mouse |\n| `keydown` | Tecla pressionada |\n| `submit` | Formulário enviado |\n| `input` | Valor do input muda |\n| `scroll` | Rolagem da página |\n\n### O Objeto Event\n\n```javascript\nbtn.addEventListener(\"click\", (event) => {\n  console.log(event.target);  // elemento clicado\n  console.log(event.type);    // \"click\"\n});\n```\n\n### preventDefault\n\n```javascript\nform.addEventListener(\"submit\", (e) => {\n  e.preventDefault(); // impede envio padrão\n  // validar e processar via JS\n});\n```\n\n### Event Delegation ✨\n\nEm vez de um listener por item, coloque **um no pai**:\n\n```javascript\ndocument.querySelector(\"#lista\").addEventListener(\"click\", (e) => {\n  if (e.target.classList.contains(\"item\")) {\n    console.log(\"Item:\", e.target.textContent);\n  }\n});\n```\n\n**Analogia do Recepcionista**: Um recepcionista na entrada direciona cada visitante, em vez de cada sala ter um porteiro.\n\n> Event delegation: 1) Menos memória, 2) Funciona com novos elementos, 3) Melhor performance.', 1, 5);

  -- Módulo 6: Programação Assíncrona
  INSERT INTO public.modulos (curso_id, nome, descricao, icone, ordem)
  VALUES (v_curso_id, 'Programação Assíncrona', 'Callbacks, Promises e async/await.', 'Cpu', 5)
  RETURNING id INTO v_mod6_id;

  INSERT INTO public.modulo_topicos (modulo_id, titulo, conteudo, ordem, moedas) VALUES
  (v_mod6_id, 'Callbacks e Promises', E'## Assíncrono: O Garçom Eficiente\n\nImagine um restaurante com **um só garçom**. Se esperasse cada prato ficar pronto, seria um desastre! Ele anota pedidos e vai atendendo enquanto a cozinha prepara. Isso é **assíncrono**!\n\n### Callbacks\n\n```javascript\nfunction buscarDados(callback) {\n  setTimeout(() => {\n    callback({ nome: \"Ana\" });\n  }, 2000);\n}\n```\n\n### Callback Hell 😱\n\n```javascript\nbuscarUsuario(id, function(u) {\n  buscarPedidos(u.id, function(p) {\n    buscarProdutos(p[0].id, function(prod) {\n      console.log(prod); // pirâmide!\n    });\n  });\n});\n```\n\n### Promises: A Solução\n\n| Estado | Significado | Analogia |\n|--------|-----------|----------|\n| pending | Aguardando | Pedido na cozinha |\n| fulfilled | Sucesso | Prato pronto! ✅ |\n| rejected | Falha | Ingrediente acabou! ❌ |\n\n```javascript\nlet promessa = new Promise((resolve, reject) => {\n  setTimeout(() => {\n    resolve({ nome: \"Ana\" });\n  }, 2000);\n});\n\npromessa\n  .then(dados => console.log(dados))\n  .catch(erro => console.error(erro))\n  .finally(() => console.log(\"Fim!\"));\n```\n\n### Encadeamento Limpo\n\n```javascript\nbuscarUsuario(id)\n  .then(u => buscarPedidos(u.id))\n  .then(p => buscarProdutos(p[0].id))\n  .then(prod => console.log(prod))\n  .catch(err => console.error(err));\n```\n\n### Promise.all vs Promise.race\n- `Promise.all` → espera **todas**\n- `Promise.race` → retorna a **primeira**', 0, 5),
  (v_mod6_id, 'Async/Await e Fetch API', E'## Async/Await: Promises com Cara Síncrona\n\nO `async/await` é \"açúcar sintático\" sobre Promises — mesmo resultado, código muito mais legível.\n\n### Comparação\n\n```javascript\n// Promise\nfunction buscar() {\n  return fetch(\"/api/dados\")\n    .then(res => res.json())\n    .then(dados => console.log(dados));\n}\n\n// Async/Await ✨\nasync function buscar() {\n  const res = await fetch(\"/api/dados\");\n  const dados = await res.json();\n  console.log(dados);\n}\n```\n\n### Fetch API\n\n```javascript\n// GET\nasync function getUsuarios() {\n  const res = await fetch(\"https://api.exemplo.com/users\");\n  if (!res.ok) throw new Error(`HTTP ${res.status}`);\n  return await res.json();\n}\n\n// POST\nasync function criarUsuario(nome, email) {\n  const res = await fetch(\"/api/users\", {\n    method: \"POST\",\n    headers: { \"Content-Type\": \"application/json\" },\n    body: JSON.stringify({ nome, email }),\n  });\n  return await res.json();\n}\n```\n\n### Tratamento de Erros\n\n```javascript\nasync function fetchSeguro(url) {\n  try {\n    const res = await fetch(url);\n    if (!res.ok) throw new Error(`HTTP ${res.status}`);\n    return await res.json();\n  } catch (err) {\n    console.error(\"Erro:\", err.message);\n    return null;\n  }\n}\n```\n\n### Paralelo com Promise.all\n\n```javascript\nconst [users, posts] = await Promise.all([\n  fetch(\"/api/users\").then(r => r.json()),\n  fetch(\"/api/posts\").then(r => r.json()),\n]);\n// Muito mais rápido que sequencial!\n```\n\n### Resumo\n\n| Abordagem | Legibilidade | Uso |\n|-----------|-------------|-----|\n| Callbacks | ⭐ | Legado |\n| Promises | ⭐⭐⭐ | Encadeamento |\n| async/await | ⭐⭐⭐⭐⭐ | Padrão moderno ✅ |\n\n> 💡 Sempre use `async/await` com `try/catch`. Sem `await`, você recebe a Promise, não o valor!', 1, 5);

  -- Resumos
  INSERT INTO public.resumos (materia, titulo, conteudo) VALUES
  ('JavaScript', 'Variáveis e Tipos de Dados em JS', E'## Resumo: Variáveis e Tipos\n\n### Variáveis\n- **`const`** → valor fixo (padrão preferido)\n- **`let`** → valor pode mudar\n- **`var`** → evite!\n\n### Tipos Primitivos\n| Tipo | Exemplo |\n|------|--------|\n| string | `\"texto\"` |\n| number | `42` |\n| boolean | `true`/`false` |\n| undefined | não atribuída |\n| null | ausência intencional |\n\n### Dicas\n- Use `===` sempre\n- `typeof null` → `\"object\"` (bug histórico)\n- Template literals: `` `Olá ${nome}` ``'),
  ('JavaScript', 'Funções e Closures em JS', E'## Resumo: Funções\n\n### Tipos\n- **Declarada**: `function f() {}` (hoisting)\n- **Arrow**: `const f = () => {}` (sem hoisting)\n\n### Closures\nFunção que \"lembra\" do escopo onde foi criada:\n```javascript\nfunction contador() {\n  let n = 0;\n  return () => ++n;\n}\n```\n\n### Escopo\n- Global → visível em todo lugar\n- Função → só dentro da função\n- Bloco → `let`/`const` ficam no `{}`'),
  ('JavaScript', 'Arrays e Objetos em JS', E'## Resumo: Estruturas de Dados\n\n### Métodos de Array\n| Método | Retorna |\n|--------|--------|\n| `map()` | Novo array |\n| `filter()` | Novo array |\n| `find()` | Um item |\n| `reduce()` | Um valor |\n\n### Destructuring\n```javascript\nlet { nome, idade } = pessoa;\nlet [a, ...rest] = array;\n```\n\n### Spread\n```javascript\nlet copia = [...array];\nlet merged = { ...obj1, ...obj2 };\n```\n\n> Objetos são por **referência**. Use spread para copiar.'),
  ('JavaScript', 'Programação Assíncrona em JS', E'## Resumo: Async\n\n### Evolução\n1. Callbacks → pirâmide ❌\n2. Promises → `.then().catch()` ✅\n3. Async/Await → padrão moderno ✅✅\n\n### Fetch\n```javascript\nasync function getData() {\n  try {\n    const res = await fetch(url);\n    return await res.json();\n  } catch (err) {\n    console.error(err);\n  }\n}\n```\n\n### Paralelo\n```javascript\nconst [a, b] = await Promise.all([\n  fetch(url1).then(r => r.json()),\n  fetch(url2).then(r => r.json()),\n]);\n```');

END $$;
