// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fizcmvavzgoaznzindwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpemNtdmF2emdvYXpuemluZHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5Mzc1MzMsImV4cCI6MjA4NjUxMzUzM30.xHcnS9LZU71krTMiHYq082zbi9cSQpCkWkR73_MjKPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});